POST http://localhost:8080/oauth/token?client_id= //TODO: insert here

###

POST http://localhost:8080/payment/create?coin=eth&usd=1.2&client_transaction_id={{$randomInt}}
Authorization: //TODO: insert here

###


POST https://stg-gateway.stockbase.io/api/payment/create
Authorization: Bearer //TODO: insert here
Content-Type: application/json
Accept: application/json

{
  "coin": "eth",
  "usd": 20,
  "client_transaction_id": {{$randomInt}}
}

###

POST https://stg-gateway.stockbase.io/oauth/token
Content-Type: application/json
Accept: application/json;

{
  "grant_type": "client_credentials",
  "client_id": //TODO: insert here,
  "client_secret"
  :
  //TODO: insert here,
}

###
